### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by rap2hpoutre** [frostly/rust-slack#11]
I asked [this](https://stackoverflow.com/questions/40021037/runtime-error-with-rust-slack-index-out-of-bounds-the-len-is-0-but-the-index-i) on SO, maybe it's relative to your package, that's why I notify you here. Feel free to close this issue if not.

**Comment by compressed** [comment]
Interesting. And using curl 0.3.7 makes the error go away?

**Comment by rap2hpoutre** [comment]
Uh... I don't know sorry, I did not test :scream: 
I just thought: "Ok 0.3.0 seems a bit old (for rust world), there are some fix pushed since last version, it's a minor version change, let's try it, cause backtrace of my error speaks about curl"

**Comment by compressed** [comment]
So changing the curl version here won't help, because most likely your binary is already using 0.3.7 for curl. I was actually able to replicate your error though using `ubuntu:16.04` docker image. The way I was able to get it was:

1. `apt-get install -y curl`
1.  `curl https://sh.rustup.rs -sSf | sh` (press 1)
1. `cargo run`
2. Wait for compilation to fail due to cc linker - `apt-get install build-essential -y`
3. `cargo run` 
4. Wait for compilation to fail due to crypto - `apt-get install libssl-dev -y`
5. `cargo run` again.. At this point, you could get one of two errors:

```
<!> Success error ^^: Curl(Error { description: "Unsupported protocol", code: 1, extra: Some("Protocol \"https\" not supported or disabled in libcurl") })
```

Or:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', ../src/libcollections/vec.rs:1265
```

which is generated on the line: `let mut easy = Easy::new()`.

I believe these errors stem from the rust build failing and then as you install the dependencies (ubuntu), the cargo dependencies end up in an invalid state.

Doing a `rm -rf target/` and re-building seems to make the error go away or to avoid it from the start, just make sure your dependencies are correct before building: `apt-get install -y build-essential curl libssl-dev`.

Let me know if that works.

**Comment by compressed** [comment]
Whoops - scratch that, the curl version changed under me :smile:, which I didn't notice.

See: https://github.com/alexcrichton/curl-rust/issues/130. v0.3.8 of curl is the fix.

I'd just run `cargo update` and you should be good to go.

**Comment by rap2hpoutre** [comment]
Great! Thanks a lot :)
